var courses=[
    {
        name: 'Cooking',
        price: 1500,
        Trainer: "Kharen Smith",
        Duration: 5,
        Text: "Learn How to cook with the specialist",
    },
    {
        name: 'Games',
        price: 1500 + "hr",
        Trainer: "Ross Taylor",
        Duration: 12,
        Text: "Games for Physical Health",
    },
    {
        name: 'Anatomy',
        price: 3000,
        Trainer: "Monica Geller",
        Duration: 18,
        Text: "Learn about Anatomy",
    },
    {
        name: 'Chemistry',
        price: 2500,
        Trainer: "John Carry",
        Duration: 22,
        Text: "Chemistry",
    },
    {
        name: 'Snake language',
        price: 1500,
        Trainer: "Tom Malfoy",
        Duration: 23,
        Text: "Snake Language",
    },
    {
        name: 'Poison',
        price: 1000,
        Trainer:"Harry Potter",
        Duration: 20,
        Text: "Poison",
    },
    {
        name: 'Wand',
        price: 1000,
        Trainer: "Ronn Weasley",
        Duration: 56,
        Text: "Wand",
    },
    {
        name: 'Dark Art',
        price: 1000,
        Trainer: "Harmione Ganger",
        Duration: 45,
        Text: "Dark Art",
    },
    {
        name: 'Invisibility',
        price: 1100,
        Trainer: "Severus Snape",
        Duration: 15,
        Text: "Invisibility",

    },
    {
        name: 'Bounty',
        price: 4500,
        Trainer:"Tom Rider",
        Duration: 13,
        Text: "Bounty",
    },
    {
        name: 'Spanish',
        price: 2500,
        Trainer: "Andre Insta",
        Duration:8,
        Text: "Spanish",
    },
    {
        name: 'Spell',
        price: 500,
        Trainer: "Lionel Messi",
        Duration:2,
        Text: "Spell",
    },
    {
        name: 'Chess',
        price: 1500,
        Trainer:"Cristiano Ronaldo",
        Duration: 31,
        Text: "Chess",
    },
    {
        name: 'Calligraphy',
        price: 1500,
        Trainer:"Neymer Jr",
        Duration:36,
        Text: "Calligraphy",
    },
    {
        name: 'Herbelogy',
        price: 1500,
        Trainer: "Sakib Al Hasan",
        Duration: 23,
        Text: "Herbelogy",
    },
    {
        name: 'Broomstick',
        price: 1000,
        Trainer:"Andre Xavi",
        Duration: 25,
        Text: "Broomstick",
    },
    {
        name: 'Dark Magic',
        price: 1500,
        Trainer: "Albus Henry",
        Duration: 24,
        Text: "Dark Magic",
    }
]
export default courses;